export const productsData = [
  {
    "name": "Fresh Apples (Pack of 4)",
    "price": 120,
    "discount": 10,
    "category": "Fruits",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh, juicy, red apples. High in fiber.",
    "image": "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400",
    "brand": "Fresh",
    "mrp": 120
  },
  {
    "name": "Organic Bananas (1 Dozen)",
    "price": 60,
    "discount": 5,
    "category": "Fruits",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet yellow bananas. Source of energy.",
    "image": "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400",
    "brand": "Organic",
    "mrp": 60
  },
  {
    "name": "Seedless Black Grapes (500g)",
    "price": 90,
    "discount": 15,
    "category": "Fruits",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet, juicy, seedless black grapes.",
    "image": "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400",
    "brand": "Seedless",
    "mrp": 90
  },
  {
    "name": "Fresh Sweet Oranges (Pack of 6)",
    "price": 100,
    "discount": 8,
    "category": "Fruits",
    "stock": 24,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Citrusy oranges. Loaded with Vitamin C.",
    "image": "https://images.unsplash.com/photo-1547514701-42782101795e?w=400",
    "brand": "Fresh",
    "mrp": 100
  },
  {
    "name": "Fresh Papaya (1 Unit)",
    "price": 70,
    "discount": 0,
    "category": "Fruits",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Ripe, sweet papaya. Ideal for breakfast.",
    "image": "https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=400",
    "brand": "Fresh",
    "mrp": 70
  },
  {
    "name": "Sweet Mango (1 kg)",
    "price": 180,
    "discount": 12,
    "category": "Fruits",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet, juicy, aromatic mangoes.",
    "image": "https://images.unsplash.com/photo-1553279768-865429fa0078?w=400",
    "brand": "Sweet",
    "mrp": 180
  },
  {
    "name": "Seedless Green Grapes (500g)",
    "price": 85,
    "discount": 10,
    "category": "Fruits",
    "stock": 22,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crisp and sweet seedless green grapes.",
    "image": "https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400",
    "brand": "Seedless",
    "mrp": 85
  },
  {
    "name": "Fresh Watermelon (1 Unit)",
    "price": 80,
    "discount": 5,
    "category": "Fruits",
    "stock": 12,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Juicy, sweet watermelon, perfect for hydration.",
    "image": "https://images.unsplash.com/photo-1589984662646-e7b2e4962f18?w=400",
    "brand": "Fresh",
    "mrp": 80
  },
  {
    "name": "Fresh Pineapple (1 Unit)",
    "price": 95,
    "discount": 8,
    "category": "Fruits",
    "stock": 18,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet and tangy fresh pineapple.",
    "image": "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400",
    "brand": "Fresh",
    "mrp": 95
  },
  {
    "name": "Fresh Pomegranate (Pack of 2)",
    "price": 130,
    "discount": 10,
    "category": "Fruits",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Premium quality pomegranates rich in antioxidants.",
    "image": "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=400",
    "brand": "Fresh",
    "mrp": 130
  },
  {
    "name": "Fresh Kiwi (Pack of 3)",
    "price": 110,
    "discount": 15,
    "category": "Fruits",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Vitamin C rich fresh kiwi fruit.",
    "image": "https://images.unsplash.com/photo-1585059895524-72359e061381?w=400",
    "brand": "Fresh",
    "mrp": 110
  },
  {
    "name": "Fresh Strawberries (200g)",
    "price": 140,
    "discount": 20,
    "category": "Fruits",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh and delicious red strawberries.",
    "image": "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400",
    "brand": "Fresh",
    "mrp": 140
  },
  {
    "name": "Guava (500g)",
    "price": 60,
    "discount": 0,
    "category": "Fruits",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh green guavas with white pulp.",
    "image": "https://images.unsplash.com/photo-1536584749557-9d7fbef8b43f?w=400",
    "brand": "Guava",
    "mrp": 60
  },
  {
    "name": "Sweet Pear (Pack of 4)",
    "price": 120,
    "discount": 5,
    "category": "Fruits",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crisp and juicy sweet pears.",
    "image": "https://images.unsplash.com/photo-1514756331096-242fdeb70d4a?w=400",
    "brand": "Sweet",
    "mrp": 120
  },
  {
    "name": "Chikoo / Sapota (500g)",
    "price": 55,
    "discount": 5,
    "category": "Fruits",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet, brown, textured sapota fruits.",
    "image": "https://images.unsplash.com/photo-1528826490691-e40df5f78235?w=400",
    "brand": "Chikoo",
    "mrp": 55
  },
  {
    "name": "Dragon Fruit (1 Unit)",
    "price": 140,
    "discount": 10,
    "category": "Fruits",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Exotic pink dragon fruit with white flesh.",
    "image": "https://images.unsplash.com/photo-1527324688151-0e627063f26f?w=400",
    "brand": "Dragon",
    "mrp": 140
  },
  {
    "name": "Fresh Tender Coconut (1 Unit)",
    "price": 65,
    "discount": 0,
    "category": "Fruits",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh coconut water rich in electrolytes.",
    "image": "https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=400",
    "brand": "Fresh",
    "mrp": 65
  },
  {
    "name": "Sweet Muskmelon (1 Unit)",
    "price": 75,
    "discount": 10,
    "category": "Fruits",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Aromatic and sweet muskmelon.",
    "image": "https://images.unsplash.com/photo-1579385960010-0931bb2514ab?w=400",
    "brand": "Sweet",
    "mrp": 75
  },
  {
    "name": "Fresh Blueberry Box (125g)",
    "price": 220,
    "discount": 15,
    "category": "Fruits",
    "stock": 12,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Imported fresh blueberries.",
    "image": "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400",
    "brand": "Fresh",
    "mrp": 220
  },
  {
    "name": "Red Cherry Box (250g)",
    "price": 180,
    "discount": 10,
    "category": "Fruits",
    "stock": 10,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet and juicy red cherries.",
    "image": "https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=400",
    "brand": "Red",
    "mrp": 180
  },
  {
    "name": "Fresh Yellow Lemons (Pack of 6)",
    "price": 30,
    "discount": 0,
    "category": "Fruits",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Tangy fresh yellow lemons.",
    "image": "https://images.unsplash.com/photo-1590502593747-42a996133562?w=400",
    "brand": "Fresh",
    "mrp": 30
  },
  {
    "name": "Sweet Lychee (500g)",
    "price": 160,
    "discount": 8,
    "category": "Fruits",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet and juicy seasonal lychee.",
    "image": "https://images.unsplash.com/photo-1601275224025-4c079555c2d3?w=400",
    "brand": "Sweet",
    "mrp": 160
  },
  {
    "name": "Juicy Peach (Pack of 4)",
    "price": 150,
    "discount": 12,
    "category": "Fruits",
    "stock": 18,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fragrant and sweet fresh peaches.",
    "image": "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=400",
    "brand": "Juicy",
    "mrp": 150
  },
  {
    "name": "Sweet Plum (500g)",
    "price": 110,
    "discount": 5,
    "category": "Fruits",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Tart and sweet red plums.",
    "image": "https://images.unsplash.com/photo-1603816656461-9c60e5dbbf9c?w=400",
    "brand": "Sweet",
    "mrp": 110
  },
  {
    "name": "Fresh Apricot (500g)",
    "price": 190,
    "discount": 10,
    "category": "Fruits",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh, velvety soft apricots.",
    "image": "https://images.unsplash.com/photo-1501747315-124a0eaca060?w=400",
    "brand": "Fresh",
    "mrp": 190
  },
  {
    "name": "Blackberry Box (150g)",
    "price": 210,
    "discount": 15,
    "category": "Fruits",
    "stock": 12,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Plump and juicy fresh blackberries.",
    "image": "https://images.unsplash.com/photo-1518635017498-87f514b751ba?w=400",
    "brand": "Blackberry",
    "mrp": 210
  },
  {
    "name": "Raspberry Box (150g)",
    "price": 230,
    "discount": 15,
    "category": "Fruits",
    "stock": 10,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Bright red, delicate fresh raspberries.",
    "image": "https://images.unsplash.com/photo-1577069861033-55d04cec4ef5?w=400",
    "brand": "Raspberry",
    "mrp": 230
  },
  {
    "name": "Custard Apple / Sitaphal (500g)",
    "price": 120,
    "discount": 10,
    "category": "Fruits",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet, creamy custard apples.",
    "image": "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=400",
    "brand": "Custard",
    "mrp": 120
  },
  {
    "name": "Sweet Lime / Mosambi (1 kg)",
    "price": 90,
    "discount": 5,
    "category": "Fruits",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh sweet lime for juicing.",
    "image": "https://images.unsplash.com/photo-1590502593747-42a996133562?w=400",
    "brand": "Sweet",
    "mrp": 90
  },
  {
    "name": "Fresh Figs (250g)",
    "price": 140,
    "discount": 10,
    "category": "Fruits",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet, soft fresh figs.",
    "image": "https://images.unsplash.com/photo-1596701062351-df1f8d368a8c?w=400",
    "brand": "Fresh",
    "mrp": 140
  },
  {
    "name": "Butter Avocado (2 Units)",
    "price": 260,
    "discount": 15,
    "category": "Fruits",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Creamy Hass avocados.",
    "image": "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400",
    "brand": "Butter",
    "mrp": 260
  },
  {
    "name": "Fresh Potatoes (1 kg)",
    "price": 30,
    "discount": 0,
    "category": "Vegetables",
    "stock": 100,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Daily essential potatoes.",
    "image": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400",
    "brand": "Fresh",
    "mrp": 30
  },
  {
    "name": "Fresh Red Tomatoes (500g)",
    "price": 25,
    "discount": 10,
    "category": "Vegetables",
    "stock": 60,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Juicy red tomatoes.",
    "image": "https://images.unsplash.com/photo-1561136594-7f68413baa99?w=400",
    "brand": "Fresh",
    "mrp": 25
  },
  {
    "name": "Fresh Onions (1 kg)",
    "price": 40,
    "discount": 5,
    "category": "Vegetables",
    "stock": 80,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Pungent red onions.",
    "image": "https://images.unsplash.com/photo-1620574387735-3624d75b2dbc?w=400",
    "brand": "Fresh",
    "mrp": 40
  },
  {
    "name": "Garlic Bulbs (250g)",
    "price": 45,
    "discount": 5,
    "category": "Vegetables",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh, strong garlic bulbs.",
    "image": "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=400",
    "brand": "Garlic",
    "mrp": 45
  },
  {
    "name": "Fresh Ginger (250g)",
    "price": 35,
    "discount": 0,
    "category": "Vegetables",
    "stock": 45,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Spicy, fibrous fresh ginger root.",
    "image": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400",
    "brand": "Fresh",
    "mrp": 35
  },
  {
    "name": "Fresh Spinach / Palak (250g)",
    "price": 20,
    "discount": 0,
    "category": "Vegetables",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Clean, iron-rich spinach leaves.",
    "image": "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400",
    "brand": "Fresh",
    "mrp": 20
  },
  {
    "name": "Cauliflower (1 Unit)",
    "price": 35,
    "discount": 0,
    "category": "Vegetables",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh white cauliflower head.",
    "image": "https://images.unsplash.com/photo-1568584711271-6c929fb49b60?w=400",
    "brand": "Cauliflower",
    "mrp": 35
  },
  {
    "name": "Green Cabbage (1 Unit)",
    "price": 30,
    "discount": 5,
    "category": "Vegetables",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crispy green cabbage head.",
    "image": "https://images.unsplash.com/photo-1611105637889-3dfa1059f8a3?w=400",
    "brand": "Green",
    "mrp": 30
  },
  {
    "name": "Red Carrots (500g)",
    "price": 40,
    "discount": 10,
    "category": "Vegetables",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet, crunchy red carrots.",
    "image": "https://images.unsplash.com/photo-1598170845058-32b996a6bd41?w=400",
    "brand": "Red",
    "mrp": 40
  },
  {
    "name": "White Radish (500g)",
    "price": 25,
    "discount": 0,
    "category": "Vegetables",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh, sharp white radish.",
    "image": "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=400",
    "brand": "White",
    "mrp": 25
  },
  {
    "name": "Green Capsicum (250g)",
    "price": 30,
    "discount": 0,
    "category": "Vegetables",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crispy green bell peppers.",
    "image": "https://images.unsplash.com/photo-1563565312874-843f7ec40034?w=400",
    "brand": "Green",
    "mrp": 30
  },
  {
    "name": "Fresh Cucumber (500g)",
    "price": 28,
    "discount": 5,
    "category": "Vegetables",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Cool and hydrating cucumbers.",
    "image": "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400",
    "brand": "Fresh",
    "mrp": 28
  },
  {
    "name": "Lady Finger / Bhindi (500g)",
    "price": 35,
    "discount": 0,
    "category": "Vegetables",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh, tender okra / lady finger.",
    "image": "https://images.unsplash.com/photo-1625938146369-adc83368bda7?w=400",
    "brand": "Lady",
    "mrp": 35
  },
  {
    "name": "Eggplant / Brinjal (500g)",
    "price": 30,
    "discount": 10,
    "category": "Vegetables",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Glossy dark purple brinjal.",
    "image": "https://images.unsplash.com/photo-1628747503898-eac65e6df1de?w=400",
    "brand": "Eggplant",
    "mrp": 30
  },
  {
    "name": "Green Peas (500g)",
    "price": 60,
    "discount": 10,
    "category": "Vegetables",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Freshly shelled green sweet peas.",
    "image": "https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?w=400",
    "brand": "Green",
    "mrp": 60
  },
  {
    "name": "Fresh Coriander (100g)",
    "price": 15,
    "discount": 0,
    "category": "Vegetables",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Freshly cut green coriander leaves.",
    "image": "https://images.unsplash.com/photo-1588879460618-9249e7d947d1?w=400",
    "brand": "Fresh",
    "mrp": 15
  },
  {
    "name": "Mint Leaves / Pudina (100g)",
    "price": 15,
    "discount": 0,
    "category": "Vegetables",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Aromatic fresh mint leaves.",
    "image": "https://images.unsplash.com/photo-1603569283847-aa295f0d016a?w=400",
    "brand": "Mint",
    "mrp": 15
  },
  {
    "name": "Fresh Beetroot (500g)",
    "price": 32,
    "discount": 5,
    "category": "Vegetables",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Nutritious deep red beetroots.",
    "image": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400",
    "brand": "Fresh",
    "mrp": 32
  },
  {
    "name": "Sweet Potato (500g)",
    "price": 35,
    "discount": 0,
    "category": "Vegetables",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Starchy, sweet potatoes.",
    "image": "https://images.unsplash.com/photo-1598170845058-32b996a6bd41?w=400",
    "brand": "Sweet",
    "mrp": 35
  },
  {
    "name": "Pumpkin (1 Unit, ~1kg)",
    "price": 40,
    "discount": 5,
    "category": "Vegetables",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet and nutritious pumpkin slices.",
    "image": "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=400",
    "brand": "Pumpkin",
    "mrp": 40
  },
  {
    "name": "Green Broccoli (1 Unit)",
    "price": 60,
    "discount": 12,
    "category": "Vegetables",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Premium fresh green broccoli.",
    "image": "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=400",
    "brand": "Green",
    "mrp": 60
  },
  {
    "name": "Button Mushrooms (200g)",
    "price": 48,
    "discount": 5,
    "category": "Vegetables",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Freshly packed button mushrooms.",
    "image": "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400",
    "brand": "Button",
    "mrp": 48
  },
  {
    "name": "Sweet Corn (2 Units)",
    "price": 30,
    "discount": 0,
    "category": "Vegetables",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet golden corn cobs.",
    "image": "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400",
    "brand": "Sweet",
    "mrp": 30
  },
  {
    "name": "Bitter Gourd / Karela (500g)",
    "price": 35,
    "discount": 10,
    "category": "Vegetables",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh bitter gourds.",
    "image": "https://images.unsplash.com/photo-1625938146369-adc83368bda7?w=400",
    "brand": "Bitter",
    "mrp": 35
  },
  {
    "name": "Bottle Gourd / Lauki (1 Unit)",
    "price": 28,
    "discount": 0,
    "category": "Vegetables",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Tender and light bottle gourd.",
    "image": "https://images.unsplash.com/photo-1587049352847-4a23e5133ec2?w=400",
    "brand": "Bottle",
    "mrp": 28
  },
  {
    "name": "Green Beans (250g)",
    "price": 25,
    "discount": 0,
    "category": "Vegetables",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crispy green string beans.",
    "image": "https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?w=400",
    "brand": "Green",
    "mrp": 25
  },
  {
    "name": "Curry Leaves (50g)",
    "price": 12,
    "discount": 0,
    "category": "Vegetables",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Aromatic curry leaves for tempering.",
    "image": "https://images.unsplash.com/photo-1627485264983-76950f52b58b?w=400",
    "brand": "Curry",
    "mrp": 12
  },
  {
    "name": "Green Chilli (100g)",
    "price": 15,
    "discount": 0,
    "category": "Vegetables",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Hot and spicy green chillies.",
    "image": "https://images.unsplash.com/photo-1607305387299-a3d9611cd46f?w=400",
    "brand": "Green",
    "mrp": 15
  },
  {
    "name": "Spring Onion (250g)",
    "price": 25,
    "discount": 5,
    "category": "Vegetables",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh spring onions with green tops.",
    "image": "https://images.unsplash.com/photo-1597362925123-77861d3fbac7?w=400",
    "brand": "Spring",
    "mrp": 25
  },
  {
    "name": "Fresh Green Chillies & Ginger Combo",
    "price": 20,
    "discount": 0,
    "category": "Vegetables",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Spicy green chillies (100g) and fresh ginger (100g).",
    "image": "https://images.unsplash.com/photo-1607305387299-a3d9611cd46f?w=400",
    "brand": "Fresh",
    "mrp": 20
  },
  {
    "name": "Lays Classic Potato Chips",
    "price": 20,
    "discount": 0,
    "category": "Snacks",
    "stock": 100,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crisp potato chips salted to perfection.",
    "image": "https://images.unsplash.com/photo-1599490659213-e2b9527b0876?w=400",
    "brand": "Lays",
    "mrp": 20
  },
  {
    "name": "Kurkure Masala Munch (Classic)",
    "price": 20,
    "discount": 0,
    "category": "Snacks",
    "stock": 80,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crunchy grain puffs loaded with Indian spices.",
    "image": "https://images.unsplash.com/photo-1621447504864-d8686e1d681c?w=400",
    "brand": "Kurkure",
    "mrp": 20
  },
  {
    "name": "Oreo Chocolate Sandwich Cookies",
    "price": 35,
    "discount": 10,
    "category": "Snacks",
    "stock": 65,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Cookies with vanilla cream filling.",
    "image": "https://images.unsplash.com/photo-1558961303-1d20210a2f43?w=400",
    "brand": "Oreo",
    "mrp": 35
  },
  {
    "name": "Act II Popcorn (Butter Pepper)",
    "price": 15,
    "discount": 0,
    "category": "Snacks",
    "stock": 70,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Instant microwaveable popcorn pack.",
    "image": "https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=400",
    "brand": "Act II",
    "mrp": 15
  },
  {
    "name": "Haldiram’s Bhujia Sev (150g)",
    "price": 40,
    "discount": 5,
    "category": "Snacks",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Spicy bean and gram flour noodles.",
    "image": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=400",
    "brand": "Haldiram",
    "mrp": 40
  },
  {
    "name": "Cadbury Dairy Milk Silk",
    "price": 80,
    "discount": 5,
    "category": "Snacks",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Smooth, creamy milk chocolate bar.",
    "image": "https://images.unsplash.com/photo-1548907040-4d42b52125ca?w=400",
    "brand": "Cadbury",
    "mrp": 80
  },
  {
    "name": "Britannia Good Day Butter Cookies",
    "price": 30,
    "discount": 0,
    "category": "Snacks",
    "stock": 60,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Rich butter cookies with smiley face pattern.",
    "image": "https://images.unsplash.com/photo-1558961303-1d20210a2f43?w=400",
    "brand": "Britannia",
    "mrp": 30
  },
  {
    "name": "Doritos Nacho Cheese Chips",
    "price": 30,
    "discount": 0,
    "category": "Snacks",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crunchy tortilla chips loaded with cheese.",
    "image": "https://images.unsplash.com/photo-1566478989037-eec170784d20?w=400",
    "brand": "Doritos",
    "mrp": 30
  },
  {
    "name": "Haldiram’s Aloo Bhujia (150g)",
    "price": 40,
    "discount": 5,
    "category": "Snacks",
    "stock": 55,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crunchy spiced potato noodle snacks.",
    "image": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=400",
    "brand": "Haldiram",
    "mrp": 40
  },
  {
    "name": "Hide & Seek Chocolate Chip Cookies",
    "price": 35,
    "discount": 5,
    "category": "Snacks",
    "stock": 45,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Premium chocolate chip cookies.",
    "image": "https://images.unsplash.com/photo-1558961303-1d20210a2f43?w=400",
    "brand": "Hide",
    "mrp": 35
  },
  {
    "name": "KitKat Chocolate Bar",
    "price": 25,
    "discount": 0,
    "category": "Snacks",
    "stock": 100,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crispy wafer fingers covered in milk chocolate.",
    "image": "https://images.unsplash.com/photo-1548907040-4d42b52125ca?w=400",
    "brand": "KitKat",
    "mrp": 25
  },
  {
    "name": "Snickers Peanut Bar (50g)",
    "price": 40,
    "discount": 0,
    "category": "Snacks",
    "stock": 80,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Nougat, caramel and peanuts covered in chocolate.",
    "image": "https://images.unsplash.com/photo-1548907040-4d42b52125ca?w=400",
    "brand": "Snickers",
    "mrp": 40
  },
  {
    "name": "Pringles Potato Chips (Sour Cream)",
    "price": 110,
    "discount": 10,
    "category": "Snacks",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Saddle-shaped potato crisps stacked in a tube.",
    "image": "https://images.unsplash.com/photo-1566478989037-eec170784d20?w=400",
    "brand": "Pringles",
    "mrp": 110
  },
  {
    "name": "Parle-G Gluco Biscuits (Pack of 4)",
    "price": 20,
    "discount": 0,
    "category": "Snacks",
    "stock": 120,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "The classic, beloved energy biscuits.",
    "image": "https://images.unsplash.com/photo-1558961303-1d20210a2f43?w=400",
    "brand": "Parle-G",
    "mrp": 20
  },
  {
    "name": "Bingo Mad Angles Achaari Masti",
    "price": 20,
    "discount": 0,
    "category": "Snacks",
    "stock": 75,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Achari flavor triangular chips.",
    "image": "https://images.unsplash.com/photo-1566478989037-eec170784d20?w=400",
    "brand": "Bingo",
    "mrp": 20
  },
  {
    "name": "Nutella Hazelnut Spread (290g)",
    "price": 320,
    "discount": 8,
    "category": "Snacks",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet spread containing cocoa and hazelnuts.",
    "image": "https://images.unsplash.com/photo-1553456558-aff63285bdd1?w=400",
    "brand": "Nutella",
    "mrp": 320
  },
  {
    "name": "McVities Digestive Biscuits (250g)",
    "price": 70,
    "discount": 5,
    "category": "Snacks",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Healthy wheat digestive biscuits.",
    "image": "https://images.unsplash.com/photo-1558961303-1d20210a2f43?w=400",
    "brand": "McVities",
    "mrp": 70
  },
  {
    "name": "Haldiram’s Kaju Katli (250g)",
    "price": 250,
    "discount": 10,
    "category": "Snacks",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Traditional Indian cashew fudge dessert.",
    "image": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=400",
    "brand": "Haldiram",
    "mrp": 250
  },
  {
    "name": "Amul Dark Chocolate Bar (150g)",
    "price": 100,
    "discount": 5,
    "category": "Snacks",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Premium 55% cocoa dark chocolate bar.",
    "image": "https://images.unsplash.com/photo-1548907040-4d42b52125ca?w=400",
    "brand": "Amul",
    "mrp": 100
  },
  {
    "name": "Britannia Marie Gold Biscuits",
    "price": 30,
    "discount": 0,
    "category": "Snacks",
    "stock": 80,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crispy tea time wheat biscuits.",
    "image": "https://images.unsplash.com/photo-1558961303-1d20210a2f43?w=400",
    "brand": "Britannia",
    "mrp": 30
  },
  {
    "name": "Roasted Salted Almonds (200g)",
    "price": 210,
    "discount": 12,
    "category": "Snacks",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Nutritious roasted and salted premium almonds.",
    "image": "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=400",
    "brand": "Roasted",
    "mrp": 210
  },
  {
    "name": "Roasted Salted Cashews (200g)",
    "price": 240,
    "discount": 12,
    "category": "Snacks",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crunchy salted premium cashews.",
    "image": "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=400",
    "brand": "Roasted",
    "mrp": 240
  },
  {
    "name": "Lays Cream & Onion Chips",
    "price": 20,
    "discount": 0,
    "category": "Snacks",
    "stock": 90,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sour cream & onion flavor potato chips.",
    "image": "https://images.unsplash.com/photo-1566478989037-eec170784d20?w=400",
    "brand": "Lays",
    "mrp": 20
  },
  {
    "name": "Sunfeast Dark Fantasy Choco Fills",
    "price": 40,
    "discount": 5,
    "category": "Snacks",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Cookies with luxurious liquid choco center.",
    "image": "https://images.unsplash.com/photo-1558961303-1d20210a2f43?w=400",
    "brand": "Sunfeast",
    "mrp": 40
  },
  {
    "name": "Kellogg’s Chocos (250g)",
    "price": 120,
    "discount": 8,
    "category": "Snacks",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Chocolate flavored wheat breakfast cereal.",
    "image": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400",
    "brand": "Kellogg’s",
    "mrp": 120
  },
  {
    "name": "Haldiram’s Soan Papdi (250g)",
    "price": 70,
    "discount": 5,
    "category": "Snacks",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Traditional flaky sweet made of chickpea flour.",
    "image": "https://images.unsplash.com/photo-1601050690597-df056fb4ce78?w=400",
    "brand": "Haldiram",
    "mrp": 70
  },
  {
    "name": "Bourbon Chocolate Biscuits",
    "price": 20,
    "discount": 0,
    "category": "Snacks",
    "stock": 100,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Classic chocolate cream sandwich biscuits.",
    "image": "https://images.unsplash.com/photo-1558961303-1d20210a2f43?w=400",
    "brand": "Bourbon",
    "mrp": 20
  },
  {
    "name": "Uncle Chipps Spicy Treat",
    "price": 20,
    "discount": 0,
    "category": "Snacks",
    "stock": 70,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Traditional spicy crinkle cut potato chips.",
    "image": "https://images.unsplash.com/photo-1566478989037-eec170784d20?w=400",
    "brand": "Uncle",
    "mrp": 20
  },
  {
    "name": "Popcorn Cheese Flavor Pack",
    "price": 15,
    "discount": 0,
    "category": "Snacks",
    "stock": 80,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Tasty cheese flavored ready-to-eat popcorn.",
    "image": "https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=400",
    "brand": "Popcorn",
    "mrp": 15
  },
  {
    "name": "Britannia 50-50 Maska Chaska",
    "price": 25,
    "discount": 0,
    "category": "Snacks",
    "stock": 85,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet and salty biscuit loaded with herbs.",
    "image": "https://images.unsplash.com/photo-1558961303-1d20210a2f43?w=400",
    "brand": "Britannia",
    "mrp": 25
  },
  {
    "name": "Coca Cola Soft Drink Can (300ml)",
    "price": 40,
    "discount": 0,
    "category": "Beverages",
    "stock": 90,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Chilled carbonated cola.",
    "image": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400",
    "brand": "Coca Cola",
    "mrp": 40
  },
  {
    "name": "Red Bull Energy Drink (250ml)",
    "price": 125,
    "discount": 8,
    "category": "Beverages",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Energy booster for late-night exams.",
    "image": "https://images.unsplash.com/photo-1542841791-1927fec16500?w=400",
    "brand": "Red Bull",
    "mrp": 125
  },
  {
    "name": "Nescafé Classic Instant Coffee (50g)",
    "price": 175,
    "discount": 5,
    "category": "Beverages",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Rich instant coffee granules.",
    "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400",
    "brand": "Nescafé",
    "mrp": 175
  },
  {
    "name": "Lipton Honey Lemon Green Tea (25 Bags)",
    "price": 150,
    "discount": 12,
    "category": "Beverages",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Detoxifying green tea leaves.",
    "image": "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=400",
    "brand": "Lipton",
    "mrp": 150
  },
  {
    "name": "Real Mixed Fruit Juice (1L)",
    "price": 110,
    "discount": 10,
    "category": "Beverages",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Mixed fruit juice blend.",
    "image": "https://images.unsplash.com/photo-1622506972776-309d426aa010?w=400",
    "brand": "Real",
    "mrp": 110
  },
  {
    "name": "Pepsi Soft Drink Can (300ml)",
    "price": 40,
    "discount": 0,
    "category": "Beverages",
    "stock": 80,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Chilled pepsi soda can.",
    "image": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400",
    "brand": "Pepsi",
    "mrp": 40
  },
  {
    "name": "Sprite Lemon Lime Drink (300ml)",
    "price": 40,
    "discount": 0,
    "category": "Beverages",
    "stock": 85,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Chilled lemon lime soft drink.",
    "image": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400",
    "brand": "Sprite",
    "mrp": 40
  },
  {
    "name": "Monster Energy Drink (350ml)",
    "price": 125,
    "discount": 5,
    "category": "Beverages",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Intense energy boost formulation.",
    "image": "https://images.unsplash.com/photo-1542841791-1927fec16500?w=400",
    "brand": "Monster",
    "mrp": 125
  },
  {
    "name": "Tropicana 100% Orange Juice (1L)",
    "price": 120,
    "discount": 10,
    "category": "Beverages",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "100% pure squeezed orange juice.",
    "image": "https://images.unsplash.com/photo-1622506972776-309d426aa010?w=400",
    "brand": "Tropicana",
    "mrp": 120
  },
  {
    "name": "Paper Boat Aamras Mango (250ml)",
    "price": 35,
    "discount": 0,
    "category": "Beverages",
    "stock": 60,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Traditional thick mango pulp beverage.",
    "image": "https://images.unsplash.com/photo-1622506972776-309d426aa010?w=400",
    "brand": "Paper Boat",
    "mrp": 35
  },
  {
    "name": "Bisleri Mineral Water (1L)",
    "price": 20,
    "discount": 0,
    "category": "Beverages",
    "stock": 150,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Purified drinking mineral water.",
    "image": "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400",
    "brand": "Bisleri",
    "mrp": 20
  },
  {
    "name": "Amul Kool Cafe Milk (200ml)",
    "price": 30,
    "discount": 5,
    "category": "Beverages",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Delicious cold coffee milk beverage.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Amul",
    "mrp": 30
  },
  {
    "name": "Amul Kool Koko Chocolate Milk",
    "price": 30,
    "discount": 5,
    "category": "Beverages",
    "stock": 45,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Yummy chocolate flavored milk drink.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Amul",
    "mrp": 30
  },
  {
    "name": "Gatorade Blue Bolt Energy (500ml)",
    "price": 60,
    "discount": 8,
    "category": "Beverages",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sports drink rich in electrolytes.",
    "image": "https://images.unsplash.com/photo-1542841791-1927fec16500?w=400",
    "brand": "Gatorade",
    "mrp": 60
  },
  {
    "name": "Tata Tea Gold Premium (250g)",
    "price": 140,
    "discount": 5,
    "category": "Beverages",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Rich aroma black tea blend.",
    "image": "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=400",
    "brand": "Tata",
    "mrp": 140
  },
  {
    "name": "Brooke Bond Taj Mahal Tea (250g)",
    "price": 195,
    "discount": 5,
    "category": "Beverages",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Premium quality black tea leaves.",
    "image": "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=400",
    "brand": "Brooke",
    "mrp": 195
  },
  {
    "name": "Bournvita Chocolate Health Drink (500g)",
    "price": 220,
    "discount": 8,
    "category": "Beverages",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Chocolate nutrition drink powder.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Bournvita",
    "mrp": 220
  },
  {
    "name": "Horlicks Health Malt Drink (500g)",
    "price": 230,
    "discount": 8,
    "category": "Beverages",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Classic malt nutrition drink powder.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Horlicks",
    "mrp": 230
  },
  {
    "name": "Sting Energy Drink (250ml)",
    "price": 20,
    "discount": 0,
    "category": "Beverages",
    "stock": 120,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Chilled red energy drink.",
    "image": "https://images.unsplash.com/photo-1542841791-1927fec16500?w=400",
    "brand": "Sting",
    "mrp": 20
  },
  {
    "name": "Appy Fizz Apple Drink (250ml)",
    "price": 20,
    "discount": 0,
    "category": "Beverages",
    "stock": 80,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sparkling apple juice drink.",
    "image": "https://images.unsplash.com/photo-1622506972776-309d426aa010?w=400",
    "brand": "Appy",
    "mrp": 20
  },
  {
    "name": "Thums Up Cola Can (300ml)",
    "price": 40,
    "discount": 0,
    "category": "Beverages",
    "stock": 95,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Strong spicy cola drink.",
    "image": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400",
    "brand": "Thums",
    "mrp": 40
  },
  {
    "name": "Fanta Orange Can (300ml)",
    "price": 40,
    "discount": 0,
    "category": "Beverages",
    "stock": 75,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Orange flavored fizzy drink.",
    "image": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400",
    "brand": "Fanta",
    "mrp": 40
  },
  {
    "name": "Real Cranberry Fruit Juice (1L)",
    "price": 120,
    "discount": 10,
    "category": "Beverages",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet & tart cranberry fruit beverage.",
    "image": "https://images.unsplash.com/photo-1622506972776-309d426aa010?w=400",
    "brand": "Real",
    "mrp": 120
  },
  {
    "name": "Real Guava Fruit Juice (1L)",
    "price": 110,
    "discount": 10,
    "category": "Beverages",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Guava nectar fruit juice.",
    "image": "https://images.unsplash.com/photo-1622506972776-309d426aa010?w=400",
    "brand": "Real",
    "mrp": 110
  },
  {
    "name": "Tang Instant Orange Mix (500g)",
    "price": 140,
    "discount": 5,
    "category": "Beverages",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Instant orange powdered drink mix.",
    "image": "https://images.unsplash.com/photo-1622506972776-309d426aa010?w=400",
    "brand": "Tang",
    "mrp": 140
  },
  {
    "name": "Yakult Probiotic Milk Drink (5 Pack)",
    "price": 80,
    "discount": 0,
    "category": "Beverages",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Probiotic milk beverage for gut health.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Yakult",
    "mrp": 80
  },
  {
    "name": "Coconut Water Tetra Pack (200ml)",
    "price": 40,
    "discount": 0,
    "category": "Beverages",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "100% natural coconut water.",
    "image": "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400",
    "brand": "Coconut",
    "mrp": 40
  },
  {
    "name": "Hershey’s Chocolate Syrup (200g)",
    "price": 120,
    "discount": 5,
    "category": "Beverages",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Classic chocolate syrup.",
    "image": "https://images.unsplash.com/photo-1553456558-aff63285bdd1?w=400",
    "brand": "Hershey’s",
    "mrp": 120
  },
  {
    "name": "BRU Instant Coffee Gold (50g)",
    "price": 180,
    "discount": 8,
    "category": "Beverages",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Premium fine-blend instant coffee.",
    "image": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400",
    "brand": "BRU",
    "mrp": 180
  },
  {
    "name": "Mineral Water Case (6x1L)",
    "price": 110,
    "discount": 5,
    "category": "Beverages",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "6 bottles of purified drinking water.",
    "image": "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400",
    "brand": "Mineral",
    "mrp": 110
  },
  {
    "name": "Amul Taaza Toned Milk (1L)",
    "price": 66,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Toned milk. Fresh daily essential.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Amul",
    "mrp": 66
  },
  {
    "name": "Amul Butter Salted (100g)",
    "price": 56,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Classic salted butter block.",
    "image": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400",
    "brand": "Amul",
    "mrp": 56
  },
  {
    "name": "Mother Dairy Plain Yogurt (400g)",
    "price": 35,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Creamy plain curd.",
    "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    "brand": "Mother Dairy",
    "mrp": 35
  },
  {
    "name": "Amul Fresh Paneer (200g)",
    "price": 90,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Soft cottage cheese block.",
    "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    "brand": "Amul",
    "mrp": 90
  },
  {
    "name": "Amul Cheese Slices (10 Slices)",
    "price": 140,
    "discount": 10,
    "category": "Dairy Products",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Creamy cheese slices.",
    "image": "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=400",
    "brand": "Amul",
    "mrp": 140
  },
  {
    "name": "Amul Masti Spiced Buttermilk (200ml)",
    "price": 15,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Spiced buttermilk for digestion.",
    "image": "https://images.unsplash.com/photo-1529258283582-7239c52bde0a?w=400",
    "brand": "Amul",
    "mrp": 15
  },
  {
    "name": "Amul Sweet Lassi (250ml)",
    "price": 25,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 45,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet and creamy yogurt beverage.",
    "image": "https://images.unsplash.com/photo-1529258283582-7239c52bde0a?w=400",
    "brand": "Amul",
    "mrp": 25
  },
  {
    "name": "Amul Fresh Cream (250ml)",
    "price": 65,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Low fat fresh cream for cooking.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Amul",
    "mrp": 65
  },
  {
    "name": "Amul Pure Cow Ghee (500ml)",
    "price": 310,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Clarified cow butter fat.",
    "image": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400",
    "brand": "Amul",
    "mrp": 310
  },
  {
    "name": "Amul Cheese Cubes (200g)",
    "price": 120,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Processed cheese blocks.",
    "image": "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=400",
    "brand": "Amul",
    "mrp": 120
  },
  {
    "name": "Amul Cheese Spread Spicy Garlic",
    "price": 90,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Spiced garlic flavored cheese spread.",
    "image": "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=400",
    "brand": "Amul",
    "mrp": 90
  },
  {
    "name": "Mother Dairy Cow Milk (500ml)",
    "price": 30,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Daily fresh cow milk packet.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Mother Dairy",
    "mrp": 30
  },
  {
    "name": "Mother Dairy Curd Cup (200g)",
    "price": 22,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Thick set curd cup.",
    "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    "brand": "Mother Dairy",
    "mrp": 22
  },
  {
    "name": "Mother Dairy Paneer Block (200g)",
    "price": 85,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Fresh and soft cottage cheese block.",
    "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    "brand": "Mother Dairy",
    "mrp": 85
  },
  {
    "name": "Amul Garlic Butter (100g)",
    "price": 62,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Garlic flavored salted butter block.",
    "image": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400",
    "brand": "Amul",
    "mrp": 62
  },
  {
    "name": "Peanut Butter Creamy (340g)",
    "price": 165,
    "discount": 10,
    "category": "Dairy Products",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "High protein creamy peanut butter.",
    "image": "https://images.unsplash.com/photo-1553456558-aff63285bdd1?w=400",
    "brand": "Peanut",
    "mrp": 165
  },
  {
    "name": "Amul Gold Full Cream Milk (1L)",
    "price": 74,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "High-fat full cream milk packet.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Amul",
    "mrp": 74
  },
  {
    "name": "Britannia Cheese Slices (200g)",
    "price": 135,
    "discount": 8,
    "category": "Dairy Products",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Individually wrapped cheese slices.",
    "image": "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=400",
    "brand": "Britannia",
    "mrp": 135
  },
  {
    "name": "Epigamia Blueberry Greek Yogurt",
    "price": 45,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Thick greek yogurt with blueberries.",
    "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    "brand": "Epigamia",
    "mrp": 45
  },
  {
    "name": "Epigamia Strawberry Greek Yogurt",
    "price": 45,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Thick greek yogurt with strawberries.",
    "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    "brand": "Epigamia",
    "mrp": 45
  },
  {
    "name": "Epigamia Mango Greek Yogurt",
    "price": 45,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Thick greek yogurt with mango pulp.",
    "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    "brand": "Epigamia",
    "mrp": 45
  },
  {
    "name": "Amul Dark Chocolate Milkshake",
    "price": 35,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Rich Belgian chocolate milkshake.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Amul",
    "mrp": 35
  },
  {
    "name": "Amul Vanilla Milkshake (200ml)",
    "price": 30,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Rich vanilla bean milkshake.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Amul",
    "mrp": 30
  },
  {
    "name": "Amul Kesar Almond Milkshake",
    "price": 35,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Kesar and real almond bits milkshake.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Amul",
    "mrp": 35
  },
  {
    "name": "Milkymist Paneer (200g)",
    "price": 90,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Freshly packed soft paneer block.",
    "image": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    "brand": "Milkymist",
    "mrp": 90
  },
  {
    "name": "Milkymist Curd (500g Pack)",
    "price": 40,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Thick set premium curd packet.",
    "image": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    "brand": "Milkymist",
    "mrp": 40
  },
  {
    "name": "Nescafé Hazelnut Cold Coffee",
    "price": 40,
    "discount": 0,
    "category": "Dairy Products",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Chilled coffee beverage with hazelnut flavor.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Nescafé",
    "mrp": 40
  },
  {
    "name": "Amul Whipping Cream (250ml)",
    "price": 80,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Whipping cream for baking and desserts.",
    "image": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
    "brand": "Amul",
    "mrp": 80
  },
  {
    "name": "Britannia Cheese Spread Classic",
    "price": 85,
    "discount": 5,
    "category": "Dairy Products",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Plain processed cheese spread.",
    "image": "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=400",
    "brand": "Britannia",
    "mrp": 85
  },
  {
    "name": "Amul Mozzarella Cheese (200g)",
    "price": 125,
    "discount": 10,
    "category": "Dairy Products",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Diced mozzarella cheese block.",
    "image": "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=400",
    "brand": "Amul",
    "mrp": 125
  },
  {
    "name": "Dettol Liquid Handwash Refill (175ml)",
    "price": 99,
    "discount": 10,
    "category": "Personal Care",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Antibacterial handwash refill.",
    "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400",
    "brand": "Dettol",
    "mrp": 99
  },
  {
    "name": "Colgate MaxFresh Toothpaste (150g)",
    "price": 110,
    "discount": 15,
    "category": "Personal Care",
    "stock": 45,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Toothpaste with cooling crystals.",
    "image": "https://images.unsplash.com/photo-1559599141-3849f2008967?w=400",
    "brand": "Colgate",
    "mrp": 110
  },
  {
    "name": "Nivea Men Shower Gel (Active Clean)",
    "price": 199,
    "discount": 20,
    "category": "Personal Care",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Cleansing shower gel with charcoal.",
    "image": "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=400",
    "brand": "Nivea",
    "mrp": 199
  },
  {
    "name": "Head & Shoulders Cool Menthol Shampoo",
    "price": 160,
    "discount": 10,
    "category": "Personal Care",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Cool menthol anti-dandruff shampoo.",
    "image": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400",
    "brand": "Head & Shoulders",
    "mrp": 160
  },
  {
    "name": "Park Avenue Deodorant Signature (150ml)",
    "price": 210,
    "discount": 25,
    "category": "Personal Care",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Long lasting masculine fragrance.",
    "image": "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400",
    "brand": "Park",
    "mrp": 210
  },
  {
    "name": "Crocin Pain Relief Tablet (Strip of 15)",
    "price": 35,
    "discount": 0,
    "category": "Medicines",
    "stock": 100,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Relief from headache and body pain.",
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    "brand": "Crocin",
    "mrp": 35
  },
  {
    "name": "Dettol Antiseptic Liquid (100ml)",
    "price": 60,
    "discount": 0,
    "category": "Medicines",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "First-aid antiseptic disinfectant.",
    "image": "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400",
    "brand": "Dettol",
    "mrp": 60
  },
  {
    "name": "Band-Aid Tough Strips (Pack of 10)",
    "price": 25,
    "discount": 0,
    "category": "Medicines",
    "stock": 120,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Adhesive plaster bandage strips.",
    "image": "https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400",
    "brand": "Band-Aid",
    "mrp": 25
  },
  {
    "name": "Volini Pain Relief Spray (40g)",
    "price": 135,
    "discount": 8,
    "category": "Medicines",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Quick action back/joint pain spray.",
    "image": "https://images.unsplash.com/photo-1550572017-edd951b55104?w=400",
    "brand": "Volini",
    "mrp": 135
  },
  {
    "name": "Eno Fruit Salt Lemon (Instant Relief)",
    "price": 10,
    "discount": 0,
    "category": "Medicines",
    "stock": 150,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Relieves acidity in 6 seconds.",
    "image": "https://images.unsplash.com/photo-1607619056574-7b8d304a3b13?w=400",
    "brand": "Eno",
    "mrp": 10
  },
  {
    "name": "Classmate Notebook (172 Pgs)",
    "price": 45,
    "discount": 5,
    "category": "Stationery",
    "stock": 80,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "High quality notebook spiral binding.",
    "image": "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400",
    "brand": "Classmate",
    "mrp": 45
  },
  {
    "name": "Santoor Gel Pens (Pack of 5 Blue)",
    "price": 50,
    "discount": 10,
    "category": "Stationery",
    "stock": 70,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Smudge-proof blue gel pens.",
    "image": "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=400",
    "brand": "Santoor",
    "mrp": 50
  },
  {
    "name": "Apsara Platinum Pencil Box (10 Pencils)",
    "price": 60,
    "discount": 0,
    "category": "Stationery",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Dark graphite pencils box.",
    "image": "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400",
    "brand": "Apsara",
    "mrp": 60
  },
  {
    "name": "Faber-Castell Textliner Highlighters",
    "price": 90,
    "discount": 10,
    "category": "Stationery",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Pack of 4 fluorescent highlighters.",
    "image": "https://images.unsplash.com/photo-1519751138087-5bf79df62d5b?w=400",
    "brand": "Faber-Castell",
    "mrp": 90
  },
  {
    "name": "Sticky Notes Pad (3x3 inch, Pastel)",
    "price": 40,
    "discount": 0,
    "category": "Stationery",
    "stock": 60,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Pastel colored sticky notes pad.",
    "image": "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400",
    "brand": "Sticky",
    "mrp": 40
  },
  {
    "name": "Plastic Bucket & Mug Combo (16L)",
    "price": 220,
    "discount": 15,
    "category": "Hostel Essentials",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Plastic bucket (16L) with matching mug.",
    "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400",
    "brand": "Plastic",
    "mrp": 220
  },
  {
    "name": "Plastic Cloth Hangers (Set of 6)",
    "price": 90,
    "discount": 10,
    "category": "Hostel Essentials",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Durable clothing hangers.",
    "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400",
    "brand": "Plastic",
    "mrp": 90
  },
  {
    "name": "Cotton Double Bedsheet with Pillows",
    "price": 399,
    "discount": 20,
    "category": "Hostel Essentials",
    "stock": 10,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "100% cotton bedshet + 2 pillowcases.",
    "image": "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400",
    "brand": "Cotton",
    "mrp": 399
  },
  {
    "name": "Godrej Round Brass Padlock (6 Levers)",
    "price": 180,
    "discount": 5,
    "category": "Hostel Essentials",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Brass padlock with 3 keys.",
    "image": "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=400",
    "brand": "Godrej",
    "mrp": 180
  },
  {
    "name": "Surf Excel Easy Wash Detergent (1kg)",
    "price": 140,
    "discount": 8,
    "category": "Hostel Essentials",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Laundry powder for bucket washing.",
    "image": "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400",
    "brand": "Surf Excel",
    "mrp": 140
  },
  {
    "name": "Type-C Fast Charging Cable (1.5m)",
    "price": 199,
    "discount": 15,
    "category": "Electronics Accessories",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Braided Type-C fast charging cable.",
    "image": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400",
    "brand": "Type-C",
    "mrp": 199
  },
  {
    "name": "Wired Earphones with Mic (Heavy Bass)",
    "price": 299,
    "discount": 20,
    "category": "Electronics Accessories",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Earphones with 3.5mm headphone jack.",
    "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
    "brand": "Wired",
    "mrp": 299
  },
  {
    "name": "Adjustable Phone Stand (Metal)",
    "price": 150,
    "discount": 10,
    "category": "Electronics Accessories",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Foldable metal table phone stand.",
    "image": "https://images.unsplash.com/photo-1586105251261-72a756497a11?w=400",
    "brand": "Adjustable",
    "mrp": 150
  },
  {
    "name": "SanDisk 64GB Flash Drive (USB 3.0)",
    "price": 449,
    "discount": 10,
    "category": "Electronics Accessories",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Compact USB 3.0 flash drive.",
    "image": "https://images.unsplash.com/photo-1601524909162-be87252be298?w=400",
    "brand": "SanDisk",
    "mrp": 449
  },
  {
    "name": "Extension Board (4 Sockets + 2 USB)",
    "price": 349,
    "discount": 15,
    "category": "Electronics Accessories",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Extension board cord with surge protector.",
    "image": "https://images.unsplash.com/photo-1558882224-cca166733360?w=400",
    "brand": "Extension",
    "mrp": 349
  },
  {
    "name": "Maggi 2-Minute Noodles (Pack of 12)",
    "price": 168,
    "discount": 5,
    "category": "Instant Food",
    "stock": 60,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Maggi instant masala noodles.",
    "image": "https://images.unsplash.com/photo-1612966608967-312ba3d2a7bc?w=400",
    "brand": "Maggi",
    "mrp": 168
  },
  {
    "name": "Yippee Magic Masala Noodles (Pack of 6)",
    "price": 90,
    "discount": 5,
    "category": "Instant Food",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Non-sticky round block noodles.",
    "image": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400",
    "brand": "Yippee",
    "mrp": 90
  },
  {
    "name": "Knorr Instant Hot & Sour Soup",
    "price": 15,
    "discount": 0,
    "category": "Instant Food",
    "stock": 80,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Instant vegetable hot and sour soup.",
    "image": "https://images.unsplash.com/photo-1547592165-e1d17fed6005?w=400",
    "brand": "Knorr",
    "mrp": 15
  },
  {
    "name": "Ready-To-Eat Dal Makhani Pack",
    "price": 85,
    "discount": 10,
    "category": "Instant Food",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Ready-to-eat cooked lentil curry pack.",
    "image": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400",
    "brand": "Ready-To-Eat",
    "mrp": 85
  },
  {
    "name": "Ching’s Secret Instant Soy Cup Noodles",
    "price": 45,
    "discount": 0,
    "category": "Instant Food",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Spicy cup noodles fork included.",
    "image": "https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=400",
    "brand": "Ching’s",
    "mrp": 45
  },
  {
    "name": "Fresh Nagpur Oranges (Pack of 6)",
    "price": 100,
    "mrp": 100,
    "discount": 10,
    "category": "Fruits",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sweet and tangy fresh oranges, high in Vitamin C.",
    "image": "https://images.unsplash.com/photo-1547514701-42782101795e?w=400",
    "brand": "Nagpur Fresh"
  },
  {
    "name": "Fresh Green Guava (500g)",
    "price": 60,
    "mrp": 60,
    "discount": 0,
    "category": "Fruits",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Crunchy green guavas with white pulp.",
    "image": "https://images.unsplash.com/photo-1536584749557-9d7fbef8b43f?w=400",
    "brand": "Fresh Farms"
  },
  {
    "name": "Maaza Mango Drink (1L)",
    "price": 65,
    "mrp": 65,
    "discount": 5,
    "category": "Beverages",
    "stock": 45,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Delicious thick mango pulp fruit drink.",
    "image": "https://images.unsplash.com/photo-1622506972776-309d426aa010?w=400",
    "brand": "Maaza"
  },
  {
    "name": "Satin Pillow Cover (Set of 2)",
    "price": 199,
    "mrp": 199,
    "discount": 10,
    "category": "Hostel Essentials",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Soft satin pillow covers for a comfortable sleep.",
    "image": "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400",
    "brand": "ComfortHome"
  },
  {
    "name": "Mesh Laundry Bag with Drawstring",
    "price": 149,
    "mrp": 149,
    "discount": 15,
    "category": "Hostel Essentials",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Durable mesh laundry bag to organize dirty clothes.",
    "image": "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400",
    "brand": "OrganizerPro"
  },
  {
    "name": "Room Trash Can / Dustbin",
    "price": 99,
    "mrp": 99,
    "discount": 0,
    "category": "Hostel Essentials",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Lightweight plastic room trash can / dustbin.",
    "image": "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400",
    "brand": "CleanMax"
  },
  {
    "name": "Godrej Aer Spray Room Freshener (240ml)",
    "price": 140,
    "mrp": 140,
    "discount": 5,
    "category": "Hostel Essentials",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Aromatic room spray freshener for fresh fragrance.",
    "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
    "brand": "Godrej"
  },
  {
    "name": "Casio Scientific Calculator FX-991ES Plus",
    "price": 1295,
    "mrp": 1295,
    "discount": 10,
    "category": "Stationery",
    "stock": 15,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Standard scientific calculator for engineering and science labs.",
    "image": "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400",
    "brand": "Casio"
  },
  {
    "name": "Luxor Whiteboard Marker (Pack of 4)",
    "price": 120,
    "mrp": 120,
    "discount": 10,
    "category": "Stationery",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Bright whiteboard markers for group study sessions.",
    "image": "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=400",
    "brand": "Luxor"
  },
  {
    "name": "Kangaroo Desktop Stapler HD-45",
    "price": 80,
    "mrp": 80,
    "discount": 5,
    "category": "Stationery",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Sturdy metal stapler with plastic top.",
    "image": "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400",
    "brand": "Kangaroo"
  },
  {
    "name": "Camel Geometry Box",
    "price": 150,
    "mrp": 150,
    "discount": 10,
    "category": "Stationery",
    "stock": 20,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Mathematical instruments geometry box.",
    "image": "https://images.unsplash.com/photo-1519751138087-5bf79df62d5b?w=400",
    "brand": "Camel"
  },
  {
    "name": "JK A4 Sheets Ream (500 Sheets)",
    "price": 320,
    "mrp": 320,
    "discount": 8,
    "category": "Stationery",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "High-quality copier paper for assignments and notes.",
    "image": "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400",
    "brand": "JK"
  },
  {
    "name": "Dettol Bathing Soap (Pack of 3)",
    "price": 135,
    "mrp": 135,
    "discount": 5,
    "category": "Personal Care",
    "stock": 45,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Antibacterial bathing soap bar.",
    "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
    "brand": "Dettol"
  },
  {
    "name": "Himalaya Purifying Neem Face Wash (100ml)",
    "price": 120,
    "mrp": 120,
    "discount": 10,
    "category": "Personal Care",
    "stock": 35,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Neem and turmeric face wash for pimple-free skin.",
    "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
    "brand": "Himalaya"
  },
  {
    "name": "Oral-B Soft Toothbrush (Pack of 2)",
    "price": 60,
    "mrp": 60,
    "discount": 0,
    "category": "Personal Care",
    "stock": 50,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Gentle cleaning bristles toothbrush.",
    "image": "https://images.unsplash.com/photo-1559599141-3849f2008967?w=400",
    "brand": "Oral-B"
  },
  {
    "name": "Parachute Pure Coconut Hair Oil (200ml)",
    "price": 90,
    "mrp": 90,
    "discount": 5,
    "category": "Personal Care",
    "stock": 30,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "100% pure coconut hair oil.",
    "image": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400",
    "brand": "Parachute"
  },
  {
    "name": "Lifebuoy Instant Hand Sanitizer (100ml)",
    "price": 50,
    "mrp": 50,
    "discount": 0,
    "category": "Personal Care",
    "stock": 60,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Kills 99.9% germs instantly.",
    "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400",
    "brand": "Lifebuoy"
  },
  {
    "name": "Premium Soft Tissue Paper Box (100 Pulls)",
    "price": 75,
    "mrp": 75,
    "discount": 5,
    "category": "Personal Care",
    "stock": 40,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Super soft and absorbent 2-ply tissue paper.",
    "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400",
    "brand": "SoftTouch"
  },
  {
    "name": "Nivea Soft Moisturizing Cream (100ml)",
    "price": 180,
    "mrp": 180,
    "discount": 10,
    "category": "Personal Care",
    "stock": 25,
    "deliveryTime": "Scheduled Delivery",
    "isAvailable": true,
    "description": "Refreshing soft moisturizing cream with Jojoba oil.",
    "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400",
    "brand": "Nivea"
  }
];
